import { AddGroup, GroupWithMovements } from "../definitions/groups";

export async function getGroups(): Promise<GroupWithMovements[]> {
  const groups: GroupWithMovements[] = [
    {
      id: 1,
      name: "Alquiler",
      description: "Pagos mensuales del departamento",
      created_at: "2024-01-10T12:00:00Z",
      movements: [
        {
          id: 101,
          details: "Pago alquiler Enero",
          date: "2024-01-05",
          created_at: "2024-01-05T10:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 50000000,
          ars_amount: 50000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 3,
        },
        {
          id: 102,
          details: "Pago alquiler Febrero",
          date: "2024-02-05",
          created_at: "2024-02-05T10:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 55000000,
          ars_amount: 55000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 3,
        },
        {
          id: 103,
          details: "Pago alquiler Marzo",
          date: "2024-03-05",
          created_at: "2024-03-05T10:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 55000000,
          ars_amount: 55000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 3,
        },
        {
          id: 104,
          details: "Pago alquiler Abril",
          date: "2024-04-05",
          created_at: "2024-04-05T10:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 60000000,
          ars_amount: 60000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 3,
        },
      ],
    },
    {
      id: 2,
      name: "Sueldos 2024",
      description: "Cobros de sueldo mensual",
      created_at: "2024-01-01T09:00:00Z",
      movements: [
        {
          id: 201,
          details: "Sueldo Enero",
          date: "2024-01-31",
          created_at: "2024-01-31T10:00:00Z",
          mov_type: "income",
          currency: "ARS",
          original_amount: 90000000,
          ars_amount: 90000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 2,
          category_id: 1,
        },
        {
          id: 202,
          details: "Sueldo Febrero",
          date: "2024-02-29",
          created_at: "2024-02-29T10:00:00Z",
          mov_type: "income",
          currency: "ARS",
          original_amount: 90000000,
          ars_amount: 90000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 2,
          category_id: 1,
        },
        {
          id: 203,
          details: "Sueldo Marzo",
          date: "2024-03-31",
          created_at: "2024-03-31T10:00:00Z",
          mov_type: "income",
          currency: "ARS",
          original_amount: 95000000,
          ars_amount: 95000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 2,
          category_id: 1,
        },
        {
          id: 204,
          details: "Bono rendimiento Q1",
          date: "2024-04-10",
          created_at: "2024-04-10T10:00:00Z",
          mov_type: "income",
          currency: "ARS",
          original_amount: 20000000,
          ars_amount: 20000000,
          exchange_rate: null,
          rate_type: null,
          account_id: 2,
          category_id: 1,
        },
      ],
    },
    {
      id: 3,
      name: "Supermercado",
      description: "Compras semanales de alimentos",
      created_at: "2024-02-01T09:00:00Z",
      movements: [
        {
          id: 301,
          details: "Compra semana 1 Febrero",
          date: "2024-02-03",
          created_at: "2024-02-03T11:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 3200000,
          ars_amount: 3200000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 2,
        },
        {
          id: 302,
          details: "Compra semana 2 Febrero",
          date: "2024-02-10",
          created_at: "2024-02-10T11:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 2800000,
          ars_amount: 2800000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 2,
        },
        {
          id: 303,
          details: "Compra semana 3 Febrero",
          date: "2024-02-17",
          created_at: "2024-02-17T11:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 3500000,
          ars_amount: 3500000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 2,
        },
        {
          id: 304,
          details: "Compra semana 1 Marzo",
          date: "2024-03-02",
          created_at: "2024-03-02T11:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 4100000,
          ars_amount: 4100000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 2,
        },
        {
          id: 305,
          details: "Compra semana 2 Marzo",
          date: "2024-03-09",
          created_at: "2024-03-09T11:00:00Z",
          mov_type: "expense",
          currency: "ARS",
          original_amount: 3800000,
          ars_amount: 3800000,
          exchange_rate: null,
          rate_type: null,
          account_id: 1,
          category_id: 2,
        },
      ],
    },
  ];

  return new Promise<GroupWithMovements[]>((resolve) => setTimeout(() => resolve(groups), 100));
}

export async function addGroup(group: AddGroup, movementIds: number[]): Promise<GroupWithMovements> {
  // invoke("add_group", { group, movementIds })
  throw new Error("Not implemented");
}

export async function deleteGroup(id: number): Promise<void> {
  // invoke("delete_group", { id })
}
